### ISSUE TITLE
bug: Invalid check on RPC id

### ISSUE THREAD

**Issue by bitlogik** [WalletConnect/rpc-proxy#170]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After sending a valid WS to open a WalletConnect v2 client to https://**relay.walletconnect.com**/, send RPC query :
`{"jsonrpc":"2.0","id":1,"method":"irn_subscribe","params":{"topic":"sometopicid"}}`

The relay service replies :
`{"id":1,"jsonrpc":"2.0","error":{"code":-32602,"message":"Request validation error: Invalid request ID"}}`

### Expected Behavior

Should work, as before.
RPC id seems to requires a large integer, representing the current time. Any low integer such as 1 or 2 is rejected.
It should be compliant with JSON-RPC, it has broken compatibility with pywalletconnect.

In the case the filtering is legitimate nad here to stay, the published walletConnect standard documentation must be update to reflect this. The examples provided in the JSON-RPC page use the value "1" which is not working anymore.

### Steps To Reproduce

After sending a valid WS to open a WalletConnect v2 client to https://relay.walletconnect.com/,
Send RPC query :
`{"jsonrpc":"2.0","id":1,"method":"irn_subscribe","params":{"topic":"sometopicid"}}`

### Environment

```markdown
Potentially all : the interface is the socket.
```

### Relevant log output

```shell
DEBUG:pywalletconnect.client_v2irn:URI WC version 2 decoding
DEBUG:pywalletconnect.client_v2irn:wc v2 URI provided decoded successfully, now starting the WalletConnect client
DEBUG:pywalletconnect.client_v2irn:Opening a WalletConnect v2 client with https://relay.walletconnect.com/?auth=eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJkaWQ6a2V5Ono2TWtndDRTeGpzdXdTeFhTeHJnTkphSFJkWXBBaURCVXpYYjdoeUZrblQ2NVdlMSIsInN1YiI6ImUyNDgxOTE3ZTUzM2VmYjUyZjdlNzFiMWQyOGE2NDQxNTQ5NGVhNWM2NGNkMWI3ZTRjODJlMWQ0NjRjNjBhY2YiLCJhdWQiOiJ3c3M6Ly9yZWxheS53YWxsZXRjb25uZWN0LmNvbSIsImlhdCI6MTY4NzAyMTgxMCwiZXhwIjoxNjg3MTA4MjEwfQ.fae2cANuViZJigjSe9XerW5yEYwhOBXOBWDFmd8bpTDO1C6XWiFcnIjjpmgf_sHOzu268l6DeYI-QsIj39S_CA&projectId=338d2404fafcd317347e4da1c3de72b5&ua=wc-2/python-1/desktop/pyWalletConnect
DEBUG:pywalletconnect.tls_socket:Socket connected
DEBUG:pywalletconnect.websocket:Connecting to WebSocket Host=relay.walletconnect.com PathTarget=/?auth=eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJkaWQ6a2V5Ono2TWtndDRTeGpzdXdTeFhTeHJnTkphSFJkWXBBaURCVXpYYjdoeUZrblQ2NVdlMSIsInN1YiI6ImUyNDgxOTE3ZTUzM2VmYjUyZjdlNzFiMWQyOGE2NDQxNTQ5NGVhNWM2NGNkMWI3ZTRjODJlMWQ0NjRjNjBhY2YiLCJhdWQiOiJ3c3M6Ly9yZWxheS53YWxsZXRjb25uZWN0LmNvbSIsImlhdCI6MTY4NzAyMTgxMCwiZXhwIjoxNjg3MTA4MjEwfQ.fae2cANuViZJigjSe9XerW5yEYwhOBXOBWDFmd8bpTDO1C6XWiFcnIjjpmgf_sHOzu268l6DeYI-QsIj39S_CA&projectId=XXXX&ua=wc-2/python-1/desktop/pyWalletConnect
DEBUG:pywalletconnect.websocket:Waiting WebSocket handshake : 1th loop.
DEBUG:pywalletconnect.websocket:Waiting WebSocket handshake : 2th loop.
DEBUG:pywalletconnect.websocket:Waiting WebSocket handshake : 3th loop.
DEBUG:pywalletconnect.websocket:WebSocket connection established.
DEBUG:pywalletconnect.client_v2irn:wc v2 URI and project id accepted
Connecting with the Dapp ...
DEBUG:pywalletconnect.client_v2irn:Sending a subscription request for d41cc7568d89560a55a04a72ebd3d34364ff474e1447e81f55fece033bd4a1df.
DEBUG:pywalletconnect.client:WalletConnect message sending to relay : {"jsonrpc":"2.0","id":1,"method":"irn_subscribe","params":{"topic":"d41cc7568d89560a55a04a72ebd3d34364ff474e1447e81f55fece033bd4a1df"}}
```

### Anything else?

This is a deviation from the [JSOP-RPC protocol. It states](https://www.jsonrpc.org/specification) one can use any string or positive integer number.
_id is an identifier established by the Client that MUST contain a String, Number. The value SHOULD normally not be Null and Numbers SHOULD NOT contain fractional parts.
The Server MUST reply with the same value in the Response object if included. This member is used to correlate the context between the two objects._

In the case this is a deviation in the walletconnect standard from the JSON-RPC, it should be duly documented and stated in the relevant place, for the client implementers.

**Comment by arein** [comment]
https://github.com/WalletConnect/walletconnect-docs/pull/775

**Comment by tekenik** [comment]
Yoyo
