### ISSUE TITLE
bug: Invalid id response value

### ISSUE THREAD

**Issue by bitlogik** [WalletConnect/rpc-proxy#171]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the JSON-RPC "id" is a string, the service at relay.walletconnect.com replies with the corresponding integer value.
This could confuse some walletConnect client, as they expect the exact same id in the reply, to associate with the query.

### Expected Behavior

As stated by [the JSON-RPC standard](https://www.jsonrpc.org/specification) :
The Server MUST reply with the same value in the Response object if included. This member is used to correlate the context between the two objects.

### Steps To Reproduce

Send a JSON-RPC request with a string (from an integer).
Example:
```
-> {"jsonrpc":"2.0","id":"2","method":"irn_subscribe","params":{"topic":"648c3584817b016fc96a14085a6a8054cdca65466d805f65598a28f3cb5ec5bf"}}
Message received : {"id":2,"jsonrpc":"2.0","error":{"code":-32602,"message":"Request validation error: Invalid request ID"}}
```

Notice the "2" (string) is converted to 2 (number).

### Environment

```markdown
All? The interface is the socket.
```

### Relevant log output

```shell
DEBUG:pywalletconnect.client:WalletConnect message sending to relay : {"jsonrpc":"2.0","id":"2","method":"irn_subscribe","params":{"topic":"648c3584817b016fc96a14085a6a8054cdca65466d805f65598a28f3cb5ec5bf"}}
DEBUG:pywalletconnect.client_v2irn:Waiting for Topic subcription ack.
DEBUG:pywalletconnect.websocket:WebSocket Text message received : {"id":2,"jsonrpc":"2.0","error":{"code":-32602,"message":"Request validation error: Invalid request ID"}}
D
```

### Anything else?

In the case this behavior is a deviation needed for walletConnect, I propose that the server rejects all id when it's a string. Also this change in JSON-RPC must be duly documented at [the relevant place in the WC standard](https://docs.walletconnect.com/2.0/specs/servers/relay/relay-server-rpc).

**Comment by arein** [comment]
Thx. Docs out of date. This is the wrong repo though so closing. https://github.com/WalletConnect/rpc-proxy/issues/171
