### ISSUE TITLE
Where's WC v2 source code?

### ISSUE THREAD

**Issue by antonio-fr** [WalletConnect/rpc-proxy#174]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I can't find the code for v2 WC relay.

### Requested Behavior

Have the source code for a v2 relay. Else the whole ecosystem would rely on a private proprietary piece of software. Providing his own relay would be difficult, hence concentrating all traffic into a private company service.
But maybe I just looked at the wrong place.

**Comment by arein** [comment]
Agreed with the points you state

https://github.com/WalletConnect/ts-relay is an implementation of the spec

Open sourcing a more recent implementation will follow shortly. You can check out my EDCON talk about the decentralization roadmap. We will also share more at ETHCC.
