### ISSUE TITLE
Export Analytics to Athena

### ISSUE THREAD

**Issue by arein** [WalletConnect/rpc-proxy#23]
In `rs-relay` we have logic to "dump" certain data (socket/messages) into parquet files. Based on certain thresholds e.g. time/file size we upload these files to S3. From there on our Athena pipeline kicks (in `data-lake` repo).

Subject of this task is only the file creation and upload part.

**Comment by chadyj** [comment]
Looking at Infura as a reference we have:

- method (eg eth_call)
- network (eg eth mainnet)
- request status (eg success/fail

Could we also get:

- host (the dapp url)
- web3modal version
- continent/country/region

And of course we grab:

- projectid

**Comment by arein** [comment]
Also: which RPC provider served the call
