### ISSUE TITLE
WalletConnect does not currently support the Chinese region?

### ISSUE THREAD

**Issue by shenhaoguangDayDayUp** [WalletConnect/rpc-proxy#89]
**Describe the bug**
If you use a VPN, you can use it. Without a VPN, you cannot use it.

**SDK Version**
 - Version [2.0.0-rc.1]

**Screenshots**
<img width="1377" alt="image" src="https://user-images.githubusercontent.com/17617821/209902827-d7795a01-6a46-4fed-b5d9-52641d3b3b9a.png">

**Comment by arein** [comment]
You can use `rpc.walletconnect.org`
